baseURL = "https://www.openskies.sh/"
languageCode = "en-us"
title = "{open}skies.sh"
theme = "hugo-ink"

copyright = "Openskies Aerial Technology Limited"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Number of characters to show in summary.
summaryLength = 20

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    # subtitle = "Opensource products and services for the drone ecosystem"

    # Content types which are included in home page recent posts list.
    mainSections = ["articles"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page", "post"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/favicon.ico"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "dark" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    #customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
    #customDarkCSS = "css/custom-dark.css"



    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
    # customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]

# Main menu which appears below site header.

[[menu.main]]
name = "All Articles"
url = "/articles"
weight = 1

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 2

[[menu.main]]
name = "About Openskies"
url = "https://about.openskies.sh"
weight = 3


# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "About"
icon = "globe"
url = "https://about.openskies.sh"


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/openskies-sh"

# Enable tags.
[taxonomies]
   category = "categories"